### ISSUE TITLE
Exception while using Testcontainers to run tests in a container

### ISSUE THREAD

**Issue by AndrewPearson** [testcontainers/testcontainers-dotnet#553] opened 2022-08-05 16:36 UTC
Running tests using Testcontainers from within a container results in exceptions being thrown. The same tests pass when run locally (i.e. not in a container).

The following is a typical stack trace of the exceptions thrown:
```
System.TypeInitializationException : The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.
---- System.InvalidOperationException : Sequence contains no elements
  Stack Trace:
     at DotNet.Testcontainers.Configurations.TestcontainersSettings.get_OS()
...
```
Is additional config required to run Testcontainers within a container? Or is this a bug?

**To Reproduce**
1. Set up an xUnit project containing a single test class, using the PostgreSqlTest test class shown on the main README for testcontainers-dotnet, using the following nuget packages:
   - Testcontainers 2.1.0
   - Npgsql 6.0,.6
   - xUnit 2.4.2
3. Add a Dockerfile to build and run the tests (using mcr.microsoft.com/dotnet/sdk:6.0).
4. Build & run the test project in a container.

**Screenshots**
```
[xUnit.net 00:00:00.71]     Tests.PostgreSqlTest.ExecuteCommand [FAIL]
  Failed Tests.PostgreSqlTest.ExecuteCommand [1 ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.
---- System.InvalidOperationException : Sequence contains no elements
  Stack Trace:
     at DotNet.Testcontainers.Configurations.TestcontainersSettings.get_OS()
   at Tests.PostgreSqlTest..ctor() in /Tests/PostgreSqlTest.cs:line 15
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
----- Inner Stack Trace -----
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty)
   at System.Linq.ParallelEnumerable.First[TSource](ParallelQuery`1 source)
   at DotNet.Testcontainers.Configurations.TestcontainersSettings..cctor()

```

**Expected behavior**
The test should pass.

**Desktop (please complete the following information):**
- Running on Windows 10 (Build 19044.1865).
- Docker Desktop For Windows 4.11.0 (83626). Using linux containers & WSL2.
- .Net SDK 6.0.302

**Comment by HofmeisterAn** [comment] 2022-08-05 16:44
Testcontainers cannot find the Docker endpoint, see: #528, #529, https://github.com/testcontainers/testcontainers-dotnet/discussions/543#discussioncomment-3299997. Add the env variable `DOCKER_HOST` e.g.

**Comment by AndrewPearson** [comment] 2022-08-05 17:41
What should DOCKER_HOST be set to for Docker running locally? host.docker.internal doesn't resolve the problem.

**Comment by HofmeisterAn** [comment] 2022-08-05 18:42
> Is additional config required to run Testcontainers within a container? Or is this a bug?

This is not a bug. **Docker** is not running inside your container. Either use a different Docker host or use something like Docker in Docker (DinD).

> What should DOCKER_HOST be set to for Docker running locally? host.docker.internal doesn't resolve the problem.

This can be any exposed Docker API endpoint. Maybe [this](https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection) helps to understand your issue too.

**Comment by AndrewPearson** [comment] 2022-08-06 21:36
Thanks for taking the time to help. I'm afraid it's just not working with DinD. I'll have to find something else.

**Comment by HofmeisterAn** [comment] 2022-08-07 07:51
> I'm afraid it's just not working with DinD.

It is working. I am using it too. Here are some more information: https://github.com/testcontainers/testcontainers-dotnet/issues/492#issuecomment-1171283803.

**Comment by HofmeisterAn** [comment] 2022-08-11 13:51
@AndrewPearson did the comment help? Do you need any further help or can we close this issue?

**Comment by AndrewPearson** [comment] 2022-08-22 16:32
@HofmeisterAn Sorry for the slow reply, I've been offline for a couple of weeks. I'm afraid the previous comment was interesting but it didn't help. There are lots of suggestions in the various links, but they're all fragments of a working solution and there's nothing I have seen that I can really use to learn how this is done. 

It's ok to close this issue.

**Comment by HofmeisterAn** [comment] 2022-08-23 13:41
No worries. The linked comment contains everything to setup an example with Docker.

**Closed as completed by HofmeisterAn** 2022-08-23 13:41 UTC
Labels: question

**Comment by AndrewPearson** [comment] 2022-08-31 21:04
I worked it out finally. Thanks for your help.

**Comment by pdevito3** [comment] 2022-10-09 22:49
> I worked it out finally. Thanks for your help.

@AndrewPearson how did you end up resolving this? getting the same error after updating the lib for my local tests

**Comment by AndrewPearson** [comment] 2022-10-11 10:56
@pdevito3 My initial requirement was to get this working in a container running locally on Docker Desktop for Windows. In the end all that was required was to map my local `/var/run/docker.sock ` as a volume in the container. 

On Windows, docker.sock is available as `//var/run/docker.sock`. This differs slightly from the path available on other OS's.

If you're using docker-compose then add a volume entry like the following to your service declaration:
```
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

```
If you're using _docker run_ then map the same volumes with the _-v_ option.

For me that was all that was required to get things working.
